name: sliver_header_delegate
description: A flexible sliver header delegate
version: 0.0.1
author: Miroslava Podybailo
homepage: https://github.com/miroslava-podybailo/flutter_sliver_header_delegate

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
